"use client";
import Link from "next/link";import {useRouter} from "next/navigation";import {useState,type FormEvent} from "react";import {ArrowRight,BookOpen,ShieldCheck} from "lucide-react";
import {configured,supabase} from "@/lib/supabase";import {vi} from "@/lib/vi";
export function AuthForm({register=false}:{register?:boolean}){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError('');setNotice('');const form=new FormData(e.currentTarget);const email=String(form.get('email'));const password=String(form.get('password'));try{const result=register?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(result.data.session){router.replace('/');}else setNotice('Kiểm tra email để xác nhận tài khoản, sau đó quay lại đăng nhập.');}catch(e){setError(e instanceof Error?e.message:'Không thể đăng nhập.');}finally{setBusy(false);}}
 return <main id="main" className="auth-page"><section className="auth-story"><Link href="/" className="brand inverse">ことば<span>kotoba</span></Link><div><p className="eyebrow">TIẾNG NHẬT, MỖI NGÀY</p><h1>Một từ mới.<br/>Một bước tiến.</h1><p>Giữ lại những điều bạn học được.<br/>Từ N5 đến N1, theo nhịp của riêng bạn.</p><div className="auth-kanji" lang="ja">学<span>まなぶ · học hỏi</span></div></div><p className="auth-footer">一日一歩 · Mỗi ngày một bước.</p></section><section className="auth-form"><BookOpen className="auth-icon" size={32}/><p className="eyebrow">GÓC HỌC CỦA BẠN</p><h2>{register?'Bắt đầu hành trình.':'Chào mừng trở lại.'}</h2><p className="muted">{register?'Tạo tài khoản để lưu từ và theo dõi tiến độ.':'Tiếp tục từ nơi bạn đã dừng lại.'}</p>
 {!configured?<div className="notice" role="status"><strong>Chưa kết nối ứng dụng</strong><p>Cần cấu hình Supabase và địa chỉ API trước khi tạo tài khoản. Xem phần khởi chạy trong README đi kèm mã nguồn.</p></div>:<form onSubmit={submit}><label>{vi.email}<input type="email" name="email" autoComplete="email" required placeholder="ban@example.com"/></label><label>{vi.password}<input type="password" name="password" autoComplete={register?'new-password':'current-password'} minLength={8} required placeholder="Ít nhất 8 ký tự"/></label>{error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<button className="primary wide" disabled={busy}>{busy?vi.loading:register?vi.register:vi.login}<ArrowRight size={18}/></button></form>}
 <p className="auth-switch">{register?'Đã có tài khoản?':'Chưa có tài khoản?'} <Link href={register?'/login':'/register'}>{register?vi.login:vi.register}</Link></p><p className="privacy"><ShieldCheck size={16}/>Từ và tiến độ được lưu riêng theo tài khoản.</p></section></main>;
}
