"use client";
import Link from "next/link";import {useState} from "react";import {Search,ArrowRight,ChevronLeft,ChevronRight,Check} from "lucide-react";
import {useDebounced,useResource} from "@/lib/use-resource";import {vi} from "@/lib/vi";import type {Item,Page,ItemType} from "@/types";import {Badge,Empty,Failure,Loading,PageHeader} from "./ui";import {ItemDetail} from "./item-detail";
export function Catalog({collection,type}:{collection:string;type:ItemType}){const [search,setSearch]=useState('');const [level,setLevel]=useState('');const [status,setStatus]=useState('');const [sort,setSort]=useState('word');const [page,setPage]=useState(0);const [selected,setSelected]=useState<Item>();const query=useDebounced(search);const params=new URLSearchParams({search:query,sort,page:String(page),size:'20'});if(level)params.set('level',level);if(status)params.set('status',status);
 const {data,error,loading,reload}=useResource<Page<Item>>(`/${collection}?${params}`);
 return <><PageHeader eyebrow={type==='VOCABULARY'?'語彙 · VOCABULARY':type==='GRAMMAR'?'文法 · GRAMMAR':'漢字 · KANJI'} title={vi.type[type]} description={type==='VOCABULARY'?'Từng từ một, mở rộng thế giới của bạn.':type==='GRAMMAR'?'Hiểu cấu trúc. Diễn đạt điều bạn muốn nói.':'Nhận mặt chữ, hiểu nghĩa, nhớ lâu hơn.'}><Link className="button primary" href={`/review?collection=${collection}&level=${level}&search=${encodeURIComponent(query)}&status=${status}`}>Luyện tập bộ lọc <ArrowRight size={17}/></Link></PageHeader>
 <div className="level-tabs" aria-label="Lọc cấp độ"><button className={!level?'selected':''} onClick={()=>{setLevel('');setPage(0);}}>{vi.all}</button>{vi.levels.map(l=><button className={l===level?'selected':''} key={l} onClick={()=>{setLevel(l);setPage(0);}}>{l}</button>)}</div>
 <div className="filterbar"><label className="search"><Search size={18}/><input aria-label="Tìm nội dung" placeholder={vi.search} value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><select aria-label="Trạng thái học" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Mọi trạng thái</option>{Object.entries(vi.status).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Sắp xếp" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="word">Theo chữ</option><option value="newest">Mới nhất</option><option value="oldest">Cũ nhất</option></select></div>
 <div className="results-meta"><span>{data?.totalElements??0} {type==='GRAMMAR'?'mẫu ngữ pháp':type==='KANJI'?'chữ Kanji':'từ vựng'}</span><span>Dữ liệu mẫu · Cấp độ tham khảo</span></div>
 {loading?<Loading/>:error?<Failure message={error} retry={reload}/>:!data?.content.length?<Empty/>:type==='KANJI'?<div className="kanji-grid">{data.content.map(item=><button className="kanji-tile" key={item.id} onClick={()=>setSelected(item)}><div><Badge level={item.jlptLevel}/>{item.status!=='NEW'&&<Check size={16}/>}</div><span className="kanji-character" lang="ja">{item.word}</span><strong>{item.meaningVi}</strong><small lang="ja">{item.onyomi}</small></button>)}</div>:<div className="catalog-list">{data.content.map(item=><button className="catalog-row" key={item.id} onClick={()=>setSelected(item)}><div className="catalog-word"><strong lang="ja" className="japanese">{item.word}</strong>{item.reading&&<span lang="ja">{item.reading}</span>}</div><div className="catalog-meaning"><strong>{item.meaningVi}</strong><span lang="ja">{item.exampleSentence}</span></div><Badge level={item.jlptLevel}/><span className={`status ${item.status!=='NEW'?'learned':''}`}>{vi.status[item.status]}</span><ArrowRight size={17}/></button>)}</div>}
 {data&&data.totalPages>1&&<nav className="pagination" aria-label="Phân trang"><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>Trước</button><span>{page+1} / {data.totalPages}</span><button disabled={page+1>=data.totalPages||loading} onClick={()=>setPage(p=>p+1)}>Sau<ChevronRight size={16}/></button></nav>}{selected&&<ItemDetail key={selected.id} item={selected} onClose={()=>setSelected(undefined)} onChange={reload}/>}</>;
}
