"use client";
import {useState} from "react";import {Check,Plus,Star} from "lucide-react";
import type {Item} from "@/types";import {api,json} from "@/lib/api";import {vi} from "@/lib/vi";import {Badge,Modal} from "./ui";
export function ItemDetail({item,onClose,onChange}:{item:Item;onClose:()=>void;onChange:()=>void}){const [current,setCurrent]=useState(item);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function change(favorite:boolean,status:Item['status']){setBusy(true);setMessage('');try{setCurrent(await api<Item>(`/items/${item.id}/state`,json('PUT',{favorite,status})));onChange();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{await api('/personal-vocabulary',json('POST',{word:current.word,reading:current.reading,meaningVi:current.meaningVi,exampleSentence:current.exampleSentence,jlptLevel:current.jlptLevel,notes:current.notes,version:0}));setMessage('Đã lưu vào Từ của tôi.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={vi.type[current.type]} onClose={onClose}><div className="detail-title"><Badge level={current.jlptLevel}/><span className="muted">{vi.status[current.status]}</span></div><h3 lang="ja" className={`japanese detail-word ${current.type==='KANJI'?'large-kanji':''}`}>{current.word}</h3>{current.type==='VOCABULARY'&&<p lang="ja" className="reading">{current.reading}</p>}<p className="detail-meaning">{current.meaningVi}</p>{current.partOfSpeech&&<p className="muted">{current.partOfSpeech}</p>}
 {current.formation&&<section className="detail-section"><h4>Cấu trúc</h4><p lang="ja" className="formation">{current.formation}</p></section>}{current.explanation&&<section className="detail-section"><h4>Cách dùng</h4><p>{current.explanation}</p></section>}
 {current.type==='KANJI'&&<div className="reading-grid"><section><h4>Âm On</h4><p lang="ja">{current.onyomi||'—'}</p></section><section><h4>Âm Kun</h4><p lang="ja">{current.kunyomi||'—'}</p></section><section><h4>Số nét</h4><p>{current.strokeCount??'—'}</p></section></div>}
 {current.exampleSentence&&<section className="example-block"><p lang="ja">{current.exampleSentence}</p>{current.exampleReading&&<small lang="ja">{current.exampleReading}</small>}<p className="muted">{current.exampleMeaningVi}</p></section>}
 {current.extraExamples&&<section className="detail-section"><h4>{current.type==='KANJI'?'Từ ghép':'Ví dụ bổ sung'}</h4><p className="preserve-lines">{current.extraExamples}</p></section>}{current.mnemonic&&<section className="detail-section"><h4>Gợi nhớ</h4><p>{current.mnemonic}</p></section>}{current.notes&&<section className="detail-section"><h4>{vi.notes}</h4><p>{current.notes}</p></section>}
 {message&&<p role="status" className="notice">{message}</p>}<div className="dialog-actions"><button disabled={busy} className="primary" onClick={()=>change(current.favorite,current.status==='NEW'?'LEARNING':'NEW')}><Check size={16}/>{current.status==='NEW'?'Đánh dấu đã học':'Đặt lại chưa học'}</button><button disabled={busy} onClick={()=>change(!current.favorite,current.status)} aria-pressed={current.favorite}><Star size={16} fill={current.favorite?'currentColor':'none'}/>{vi.favorite}</button>{current.type!=='PERSONAL'&&<button disabled={busy} onClick={save}><Plus size={16}/>Lưu từ</button>}</div></Modal>;
}
