"use client";
import {useState} from "react";import {Star,Trash2,Check,Save,Ellipsis} from "lucide-react";
import type {Item,PersonalInput} from "@/types";import {api,json} from "@/lib/api";import {vi} from "@/lib/vi";
export function personalInput(i:Item):PersonalInput{return {word:i.word,meaningVi:i.meaningVi,exampleSentence:i.exampleSentence||'',reading:i.reading||'',jlptLevel:i.jlptLevel,notes:i.notes||'',version:i.version};}
export function PersonalRow({item,onChange,onDelete,onMore}:{item:Item;onChange:()=>void;onDelete:()=>void;onMore:()=>void}){const [draft,setDraft]=useState(personalInput(item));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const dirty=JSON.stringify(draft)!==JSON.stringify(personalInput(item));
 async function save(){if(!draft.word.trim()||!draft.meaningVi.trim()){setError('Cần nhập từ và nghĩa.');return;}setBusy(true);setError('');try{await api(`/personal-vocabulary/${item.id}`,json('PUT',draft));onChange();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function state(favorite:boolean,status:Item['status']){setBusy(true);setError('');try{await api(`/items/${item.id}/state`,json('PUT',{favorite,status}));onChange();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <tr><td><button disabled={busy} className={`icon star ${item.favorite?'on':''}`} aria-label={vi.favorite+' '+item.word} aria-pressed={item.favorite} onClick={()=>state(!item.favorite,item.status)}><Star size={17} fill={item.favorite?'currentColor':'none'}/></button></td><td><input className="inline-input japanese" aria-label={`Từ: ${item.word}`} value={draft.word} maxLength={200} disabled={busy} onChange={e=>setDraft({...draft,word:e.target.value})}/>{item.reading&&<small lang="ja">{item.reading}</small>}</td><td><input className="inline-input" aria-label={`Nghĩa của ${item.word}`} value={draft.meaningVi} maxLength={1000} disabled={busy} onChange={e=>setDraft({...draft,meaningVi:e.target.value})}/></td><td><input className="inline-input" aria-label={`Ví dụ của ${item.word}`} value={draft.exampleSentence} maxLength={2000} disabled={busy} onChange={e=>setDraft({...draft,exampleSentence:e.target.value})}/></td><td><div className="row-actions">{dirty?<><button className="icon accent" disabled={busy} aria-label={`Lưu ${item.word}`} onClick={save}><Save size={18}/></button><button className="text-button" disabled={busy} onClick={()=>setDraft(personalInput(item))}>Hủy</button></>:<><button className={`icon ${item.status!=='NEW'?'accent':''}`} disabled={busy} aria-label={`Đánh dấu đã học ${item.word}`} aria-pressed={item.status!=='NEW'} onClick={()=>state(item.favorite,item.status==='NEW'?'LEARNING':'NEW')}><Check size={18}/></button><button className="icon" disabled={busy} aria-label={`Chi tiết ${item.word}`} onClick={onMore}><Ellipsis size={18}/></button><button className="icon danger" disabled={busy} aria-label={`Xóa ${item.word}`} onClick={onDelete}><Trash2 size={16}/></button></>}</div>{error&&<p role="alert" className="error-text">{error}</p>}</td></tr>;
}
