"use client";
import Link from "next/link";import {useState,useRef,type FormEvent} from "react";import {Plus,Search,ArrowRight,NotebookPen} from "lucide-react";
import {useResource,useDebounced} from "@/lib/use-resource";import {api,json} from "@/lib/api";import type {Item,Page,PersonalInput} from "@/types";import {vi} from "@/lib/vi";import {Badge,Loading,Empty,Failure,Modal,PageHeader} from "./ui";import {PersonalRow,personalInput} from "./personal-row";
const blank:PersonalInput={word:'',meaningVi:'',exampleSentence:'',reading:'',jlptLevel:null,notes:'',version:0};
export function Personal(){const [draft,setDraft]=useState(blank);const [search,setSearch]=useState('');const [sort,setSort]=useState('newest');const [favorites,setFavorites]=useState(false);const [page,setPage]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [remove,setRemove]=useState<Item>();const [editing,setEditing]=useState<Item>();const [extra,setExtra]=useState<PersonalInput>(blank);const first=useRef<HTMLInputElement>(null);const query=useDebounced(search);const {data,loading,error,reload}=useResource<Page<Item>>(`/personal-vocabulary?${new URLSearchParams({search:query,sort,favorites:String(favorites),page:String(page),size:'20'})}`);
 async function add(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{await api('/personal-vocabulary',json('POST',draft));setDraft(blank);setPage(0);setMessage('Đã lưu từ mới.');reload();first.current?.focus();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function deleteItem(){if(!remove)return;setBusy(true);setMessage('');try{await api(`/personal-vocabulary/${remove.id}`,{method:'DELETE'});setRemove(undefined);if(data?.content.length===1&&page>0)setPage(p=>p-1);reload();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function edit(e:FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setMessage('');try{await api(`/personal-vocabulary/${editing.id}`,json('PUT',extra));setEditing(undefined);reload();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <><PageHeader eyebrow="MY NOTEBOOK · マイ単語帳" title={vi.personal} description="Gặp một từ hay? Giữ lại ngay ở đây."><Link className="button" href="/review?collection=personal-vocabulary">Ôn từ của tôi <ArrowRight size={17}/></Link></PageHeader>
 <section className="quick-add"><div className="section-label"><Plus size={17}/><strong>Lưu nhanh một từ</strong><span>Chỉ cần từ và nghĩa</span></div><form onSubmit={add}><label><span>{vi.word}</span><input ref={first} lang="ja" required maxLength={200} placeholder="見積もり" value={draft.word} onChange={e=>setDraft({...draft,word:e.target.value})}/></label><label><span>{vi.meaning}</span><input required maxLength={1000} placeholder="báo giá / ước tính" value={draft.meaningVi} onChange={e=>setDraft({...draft,meaningVi:e.target.value})}/></label><label className="example-input"><span>{vi.example} <small>không bắt buộc</small></span><input maxLength={2000} placeholder="見積もりを確認してください。" value={draft.exampleSentence} onChange={e=>setDraft({...draft,exampleSentence:e.target.value})}/></label><button className="primary" disabled={busy}><Plus size={18}/>{vi.add}</button></form><small>Nhấn Enter để lưu · Có thể bổ sung cách đọc và ghi chú sau</small></section>
 {message&&!remove&&!editing&&<p className="notice" role="status">{message}</p>}<div className="filterbar"><label className="search"><Search size={18}/><input placeholder="Tìm trong sổ từ của bạn…" aria-label="Tìm từ của tôi" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><label className="check-label"><input type="checkbox" checked={favorites} onChange={e=>{setFavorites(e.target.checked);setPage(0);}}/>Đã gắn sao</label><select aria-label="Sắp xếp" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="newest">Mới nhất</option><option value="oldest">Cũ nhất</option><option value="word">Theo chữ</option></select></div>
 <div className="results-meta"><span>{data?.totalElements??0} từ đã lưu</span><span>Sửa trực tiếp rồi nhấn biểu tượng lưu</span></div>{loading?<Loading/>:error?<Failure message={error} retry={reload}/>:!data?.content.length?<Empty><NotebookPen size={32}/><h3>{query||favorites?'Không tìm thấy từ phù hợp.':'Bạn chưa lưu từ nào.'}</h3><p>Một từ nhỏ hôm nay, một vốn từ lớn ngày mai.</p><button onClick={()=>first.current?.focus()}>{query||favorites?'Thêm từ mới':'Thêm từ đầu tiên'}</button></Empty>:<div className="table-scroll"><table className="personal-table"><thead><tr><th aria-label="Yêu thích"/><th>{vi.word}</th><th>{vi.meaning}</th><th>{vi.example}</th><th><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{data.content.map(i=><PersonalRow key={`${i.id}-${i.version}-${i.status}-${i.favorite}`} item={i} onChange={reload} onDelete={()=>{setRemove(i);setMessage('');}} onMore={()=>{setEditing(i);setExtra(personalInput(i));setMessage('');}}/>)}</tbody></table></div>}
 {data&&data.totalPages>1&&<nav className="pagination" aria-label="Phân trang"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Trước</button><span>{page+1} / {data.totalPages}</span><button disabled={page+1>=data.totalPages} onClick={()=>setPage(p=>p+1)}>Sau</button></nav>}
 {remove&&<Modal title="Xóa từ này?" onClose={()=>{if(!busy)setRemove(undefined);}}><p><strong lang="ja">{remove.word}</strong> cùng lịch sử ôn của từ này sẽ bị xóa.</p>{message&&<p role="alert" className="error-text">{message}</p>}<div className="dialog-actions"><button disabled={busy} onClick={()=>setRemove(undefined)}>{vi.cancel}</button><button disabled={busy} className="destructive" onClick={deleteItem}>{vi.delete}</button></div></Modal>}
 {editing&&<Modal title="Chỉnh sửa từ" onClose={()=>{if(!busy)setEditing(undefined);}}><Badge level={editing.jlptLevel}/><form className="edit-form" onSubmit={edit}><label>{vi.word}<input required maxLength={200} value={extra.word} onChange={e=>setExtra({...extra,word:e.target.value})}/></label><label>{vi.meaning}<input required maxLength={1000} value={extra.meaningVi} onChange={e=>setExtra({...extra,meaningVi:e.target.value})}/></label><label>{vi.reading}<input maxLength={300} value={extra.reading} onChange={e=>setExtra({...extra,reading:e.target.value})}/></label><label>Cấp độ<select value={extra.jlptLevel||''} onChange={e=>setExtra({...extra,jlptLevel:e.target.value as PersonalInput['jlptLevel']||null})}><option value="">Chưa phân loại</option>{vi.levels.map(l=><option key={l}>{l}</option>)}</select></label><label>{vi.example}<textarea maxLength={2000} value={extra.exampleSentence} onChange={e=>setExtra({...extra,exampleSentence:e.target.value})}/></label><label>{vi.notes}<textarea maxLength={8000} value={extra.notes} onChange={e=>setExtra({...extra,notes:e.target.value})}/></label>{message&&<p role="alert" className="error-text">{message}</p>}<button disabled={busy} className="primary">{vi.save}</button></form></Modal>}</>;
}
