"use client";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {useEffect,useState,type ReactNode} from "react";
import {LayoutDashboard,BookOpen,NotebookPen,Languages,Repeat2,ChartNoAxesCombined,Settings,LogOut,Menu,X,ArrowUpRight} from "lucide-react";
import {vi} from "@/lib/vi";import {useAuth} from "./auth-provider";import {supabase} from "@/lib/supabase";import {Loading} from "./ui";import {api} from "@/lib/api";import type {Settings as UserSettings} from "@/types";
const nav=[['/',vi.dashboard,LayoutDashboard],['/vocabulary',vi.vocabulary,BookOpen],['/grammar',vi.grammar,NotebookPen],['/kanji',vi.kanji,Languages],['/review',vi.review,Repeat2],['/personal-vocabulary',vi.personal,NotebookPen],['/progress',vi.progress,ChartNoAxesCombined],['/settings',vi.settings,Settings]] as const;
export function applyTheme(theme:string){const dark=theme==='dark'||theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('kotoba-theme',theme);}
export function Shell({children}:{children:ReactNode}){const path=usePathname();const router=useRouter();const {session,loading}=useAuth();const [open,setOpen]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(!loading&&!session)router.replace('/login');},[loading,session,router]);
 useEffect(()=>{applyTheme(localStorage.getItem('kotoba-theme')||'system');const media=matchMedia('(prefers-color-scheme: dark)');const change=()=>applyTheme(localStorage.getItem('kotoba-theme')||'system');media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{if(session)api<UserSettings>('/settings').then(s=>applyTheme(s.theme)).catch(()=>{});},[session]);
 if(loading||!session)return <Loading/>;
 return <div className="app-shell"><header className="mobile-header"><Link className="brand" href="/">ことば<span>kotoba</span></Link><button className="icon" aria-label="Mở menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<button className="nav-overlay" aria-label="Đóng menu" onClick={()=>setOpen(false)}/>}
 <aside className={`sidebar ${open?'open':''}`}><Link className="brand" href="/">ことば<span>kotoba<span className="brand-caption">JAPANESE, EVERY DAY</span></span></Link><p className="nav-caption">KHÔNG GIAN HỌC</p><nav>{nav.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={path===href?'active':''} aria-current={path===href?'page':undefined}><Icon size={19}/>{label}</Link>)}</nav><div className="sidebar-note"><span lang="ja">一日一歩</span><p>Mỗi ngày một bước.</p><Link href="/personal-vocabulary">Lưu một từ mới <ArrowUpRight size={15}/></Link></div><div className="account"><span className="avatar">{session.user.email?.[0]?.toUpperCase()||'K'}</span><div><strong>Góc học của bạn</strong><small>{session.user.email}</small></div><button className="icon" aria-label={vi.logout} onClick={async()=>{const result=await supabase?.auth.signOut();if(result?.error)setError(result.error.message);else router.replace('/login');}}><LogOut size={17}/></button></div>{error&&<p role="alert">{error}</p>}</aside>
 <main id="main" className="workspace"><div className="topline"><span>Học tiếng Nhật <span className="separator">/</span> {nav.find(n=>n[0]===path)?.[1]}</span><span className="top-japanese" lang="ja">継続は力なり</span></div>{children}<footer className="workspace-footer">ことば <span>Kiến thức lớn lên từ những điều nhỏ.</span></footer></main></div>;
}
