server:
  port: ${PORT:8080}

spring:
  web:
    error:
      include-message: never

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}